name: Build and deploy Python app with SocketIO to Azure Web App without Gunicorn

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the application
        run: python app.py build

      - name: Deploy the application
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bettingTrial1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_83612F424D494C3BBE8EB1E4B47DFF59 }}
          startup-command: |
            source venv/bin/activate
            python app.py run --socketio
